# Generated by Django 2.1.2 on 2018-12-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='client_uuid',
            field=models.ForeignKey(default='f32ec49a-e1be-456e-9b61-352f011ade20', on_delete=django.db.models.deletion.CASCADE, related_name='client_customers', to='userprofile.Client'),
            preserve_default=False,
        ),
    ]
