# Generated by Django 2.1.2 on 2018-12-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_customer_client_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='StoreImages/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
