# Generated by Django 2.1.2 on 2018-12-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('organizations', '0003_auto_20181205_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofsale',
            name='client_pos_uuid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='pointofsale',
            unique_together={('client_pos_uuid', 'client_uuid')},
        ),
    ]
