# Generated by Django 2.1.2 on 2018-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('organizations', '0004_auto_20181205_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlines',
            name='client_customer_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client_transaction_uuid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionlines',
            name='client_transaction_uuid',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('client_transaction_uuid', 'client_uuid')},
        ),
    ]
