# Generated by Django 2.1.2 on 2018-12-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20181211_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlines',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], default=None, null=True),
        ),
    ]
