# Generated by Django 2.1.2 on 2018-12-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20181212_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='hardware_mac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
